### PR TITLE
ENH: Add parametric characters

### PR DESCRIPTION
**Pull request by tejesh0**

### CODE REVIEW

**Comment by sanand0** [comment]
- [x] This needs to be MUCH faster. Flubber is slowing it down. Please work with Ramya to create characters with the same number of nodes in a path. Use D3 path interpolation.
- [x] See if you can avoid touching the DOM -- potentially using shadow DOM fragments

**Comment by tejesh0** [comment]
https://www.bennadel.com/blog/2281-jquery-appends-multiple-elements-using-efficient-document-fragments.htm

**Comment by sanand0** [comment]
Functional review comments

- [ ] OPTIONAL: Can we eliminate the flicker?
proxy

- [ ] OPTIONAL: Can we add ticks at 25%, 50%, 75% and 100% like this? Step 0.01 is fine.
image

- [x] OPTIONAL: Sometimes, it doesn't remove the previous element before adding the new one. See image below
image

**Comment by sanand0** [comment]
Code review comments

- [x] CRITICAL: Rename the `param` attribute to `continuous`

- [x] CRITICAL: Comicgen.js cannot depend on jQuery in comicgen.js. Remove it. `$.get` and `$()` cannot be used. (Note: script.js can use it.)

- [x] Simply the function and add a comment explaining `var img = row.file.replace(/\$([a-z]*)/g, function (match, group) { return group == row.param ? filename : attrs[group] })`

- [x] `$.when(...parametricUrls.map(function(d) {return d.getRequest}))` can be `    $.when(...parametricUrls.map(d => d.getRequest))`

- [x] Move `unit_node = node.querySelector('svg g')` out of every loop -- it's static

- [x] This snippet can just be `all_character_tags = node.querySelector('svg g').children`?
```js
  var original_id = node.querySelector(`svg g`).id
  var all_character_tags = node.querySelectorAll('#'+original_id + ' *')
```
- [x] Use `interpolate_generic_attr` instead of `interpolate_shape_attr` and eliminate `interpolate_shape_attr`

- [x] Eliminate `interpolatorMap`. Use `interpolate_path_d` if `d`. Else use `interpolate_generic_attr`

- [x] Eliminate `elementTypes`. Interpolate specific attributes (cx, cy, rx, ry, r, d, transform, fill, stroke, stroke-width) for all shapes

- [x] Test this on multiple browsers. `querySelectorAll` results do not support `.forEach`

- [x] Eliminate `if(!character_tag.id) return` or comment on why we need it.

- [x] `var real_element = node.querySelector(`#${character_tag.id}`)` is the same as `real_element = character_tag`. Similarly, improve `start_element` and `end_element`. This really needs to be cleaned up! 

- [x] Add a comment on why we are using `maxSegmentLength: 5`. We will forget this

**Comment by sanand0** [comment]
- [x] Remove rollup. We ignore IE
- [x] Use `=>` arrow functions consistently
- [x] Can we shorten `node.querySelector('svg g').querySelectorAll('*')`
- [x] Add a `TODO: Refactor to remove use of IDs` where `.id` is used

**Pull request merged**
