### PR TITLE
FIX: save as png doesn't work properly for Dee, Dey, Priya & Ringo. F…

### PR DESCRIPTION
**Pull request by tejesh0**
…ixes #39

### CODE REVIEW

**Comment by tejesh0** [comment]
@sanand0 I did not use Puppeteer based SVG to png converter because [svg-png-converer](https://github.com/cancerberoSgx/univac/tree/master/svg-png-converter) uses FabricJS internally to have the same API for both browser and node.js environments.

This helps us be sure if pngs are converted well for the svgs, then gramener.com/comicgen app also will work fine.

**Comment by sanand0** [comment]
svg-png-converter fails on Windows, @tejesh95 -- this may also mean that the library is not mature enough. Please take a look. I'll merge once this runs on Windows, and am a bit more comfortable with the library's stability.

```bash
$ yarn add svg-png-converter
yarn add v1.17.3
...
error Command failed.
Exit code: 128
Command: git
Arguments: clone https://github.com/jankovicsandras/imagetracerjs.git C:\Users\anand\AppData\Local\Yarn\Cache\v4\.tmp\9d1a5040f7226706aef7c3bf70a5551a
Directory: D:\site\gramener.com\viz\comicgen
Output:
Cloning into 'C:\Users\anand\AppData\Local\Yarn\Cache\v4\.tmp\9d1a5040f7226706aef7c3bf70a5551a'...
fatal: Invalid path '/cygdrive/d/site/gramener.com/viz/comicgen/C:\Users\anand\AppData\Local\Yarn\Cache\v4\.tmp\9d1a5040f7226706aef7c3bf70a5551a': No such file or directory
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by tejesh0** [comment]
@sanand0 I have removed `svg-png-converter` dependency. 

Added fabricjs library as a dependency. Please review it again?

**Comment by sanand0** [comment]
Works great!

Suggestions:

- [ ] Increase facesketch and humaaans PNG resolution -- ensuring height=600
- [x] Use a progress indicator like Python's tqdm for `png.js`
- [x] Move `png.js` into `build/<something>.js`
- [x] Move `png.sh` into `build/<something>.sh`
- [x] Update the docs

**Comment by tejesh0** [comment]
higher PNG resolution for facesketch and humaans is not easy with this PR.

Opened new PR which uses puppeteer https://github.com/gramener/comicgen/pull/65

**Pull request closed without merging**
